version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: sqlite3.Dockerfile
    container_name: "kuuf-library"
    env_file: ./.env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=file:kuuf-library.db