version: '3.1'
services:
  web:
    build:
      context: .
      args:
        - CGO_ENABLED=1
    container_name: "kuuf-library"
    env_file: ./.env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=file:mnt/kuuf-library.db
    volumes:
      - ${PWD}/docker:/app/mnt